# Since this is production environment, chart updates require a manual bump
# REnovate updates may be considered in the future
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: demo-company-chart
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "15m"
spec:
  type: OCIArtifactTag
  url: oci://ghcr.io/tpeh-demo-company/platform-helm-chart/demo-company
  filter:
    # fixed tag for prod
    semver: "1.0.2"
    limit: 1
---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: demo-app-image
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
  type: OCIArtifactTag
  url: oci://ghcr.io/tpeh-demo-company/platform-demo-app
  filter:
    # only semver tags for prod
    semver: ">=1.0.0"
    limit: 1
