apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - inputprovider.yaml

patches:
  - target:
      kind: ResourceSet
      name: demo-app
    patch: |
      - op: replace
        path: /spec/resources/2/spec/values/httpRoute/hostnames/0
        value: "demo.app-dev.local"
