# Since this is staging environment , updated to the chart can be automatic
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: demo-company-chart
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "15m"
spec:
  type: OCIArtifactTag
  url: oci://ghcr.io/tpeh-demo-company/platform-demo-app
  filter:
    semver: ">=1.0.0"
    limit: 1
---
# The exported outputs are:
#
# id: the Adler-32 checksum of the tag name (type string).
# tag: the tag name (type string).
# digest: the SHA256 digest corresponding to the tag in the format sha256:<hash> (type string).
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: demo-app-image
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
  type: OCIArtifactTag
  url: oci://ghcr.io/tpeh-demo-company/platform-demo-app
  filter:
    # commit sha
    includeTag: "^[a-f0-9]{40}$"
    limit: 1